"""
app/discovery/waf_detector.py
WAF (Web Application Firewall) Fingerprinter & Smart Evasion Engine
Identifies WAF technologies and recommends adaptive payload mutation strategies.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional, Tuple


class WafDetector:
    SIGNATURES = {
        "Cloudflare": {
            "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
            "server": ["cloudflare"],
            "cookies": ["__cfduid", "cf_clearance"],
            "body_patterns": [r"cloudflare-nginx", r"attention required! \| cloudflare", r"ray id: [a-f0-9]+"],
            "evasion_hints": [
                "Gunakan origin IP direct probe (bypass DNS proxy)",
                "Coba Header override: X-Forwarded-Host, CF-Connecting-IP spoofing",
                "Terapkan URL encoding ganda (%2527) & comment fragmentation (UN/**/ION)",
            ]
        },
        "AWS WAF": {
            "headers": ["x-amz-cf-id", "x-amzn-requestid", "x-amz-id-2"],
            "server": ["awselb", "amazon"],
            "cookies": ["awsalb", "awsalbcors"],
            "body_patterns": [r"403 forbidden.*aws", r"request blocked by aws waf"],
            "evasion_hints": [
                "Coba chunked transfer encoding (Transfer-Encoding: chunked)",
                "Terapkan casing random (sELecT vs select)",
                "Gunakan parameter pollution: id=1&id=2",
            ]
        },
        "Akamai": {
            "headers": ["x-akamai-transformed", "akamai-origin-hop", "x-akamai-request-id"],
            "server": ["akamaighost"],
            "cookies": ["akacd_", "ak_bmsc"],
            "body_patterns": [r"access denied.*akamai", r"reference #18\.[a-f0-9]+"],
            "evasion_hints": [
                "Bypass via HTTP/2 frame multiplexing & header case mutation",
                "Eksplorasi whitespace alternative: %09, %0a, %0b, %0c, %0d, %a0",
                "Gunakan inline comment injection",
            ]
        },
        "Imperva Incapsula": {
            "headers": ["x-iinfo", "x-cdn"],
            "server": ["incapsula"],
            "cookies": ["incap_ses", "visid_incap", "nlbi_"],
            "body_patterns": [r"incapsula incident id", r"_incapsula_resource"],
            "evasion_hints": [
                "Coba HTTP Parameter Pollution (HPP)",
                "Gunakan JSON/XML wrapper payload transformation",
                "Terapkan null byte injection (%00) pada file extension checks",
            ]
        },
        "ModSecurity / OWASP CRS": {
            "headers": ["x-mod-security", "mod_security"],
            "server": ["mod_security", "modsecurity"],
            "cookies": [],
            "body_patterns": [r"mod_security", r"this error was generated by mod_security", r"owasp_crs"],
            "evasion_hints": [
                "Manfaatkan multipart/form-data boundary whitespace mismatch",
                "Coba SQLi concatenation: concat('a','b') atau char(97,98)",
                "Gunakan backslash escaping untuk bypass regex filter",
            ]
        },
        "F5 BIG-IP ASM": {
            "headers": ["x-cnection", "x-wa-info"],
            "server": ["big-ip", "f5"],
            "cookies": ["bigipserver", "ts[0-9a-f]+"],
            "body_patterns": [r"the requested url was rejected\. please consult with your administrator", r"f5 networks"],
            "evasion_hints": [
                "Gunakan HTTP request smuggling / TE.CL desync jika didukung",
                "Gunakan URL path normalization tricks (/./, /%2e/, /..;/)",
            ]
        },
        "Fastly": {
            "headers": ["x-fastly-request-id", "fastly-debug-digest", "x-served-by"],
            "server": ["fastly"],
            "cookies": [],
            "body_patterns": [r"fastly error: unknown domain"],
            "evasion_hints": [
                "Coba Fastly cache poisoning via Host / X-Forwarded-Host injection",
            ]
        },
        "Sucuri Cloudproxy": {
            "headers": ["x-sucuri-id", "x-sucuri-cache"],
            "server": ["sucuri/cloudproxy"],
            "cookies": ["sucuri_cloudproxy_uuid_"],
            "body_patterns": [r"access denied - sucuri website firewall"],
            "evasion_hints": [
                "Gunakan Base64 / Hex encoding pada parameter yang mendukung decode otomatis",
            ]
        },
    }

    @classmethod
    def analyze_response(
        cls,
        status_code: int,
        headers: Dict[str, str],
        cookies: Optional[Dict[str, str]] = None,
        body: str = "",
    ) -> Dict[str, Any]:
        """Analyze HTTP response headers, server, cookies, and body to identify WAF."""
        headers_lower = {k.lower(): str(v).lower() for k, v in (headers or {}).items()}
        cookies_lower = {k.lower(): str(v).lower() for k, v in (cookies or {}).items()}
        server_header = headers_lower.get("server", "")
        body_lower = (body or "").lower()

        detected_wafs = []

        for vendor, rule in cls.SIGNATURES.items():
            confidence = 0.0
            matched_reasons = []

            # Check specific headers
            for h in rule["headers"]:
                if h in headers_lower:
                    confidence += 0.45
                    matched_reasons.append(f"Header '{h}' matches {vendor}")

            # Check server header
            for s in rule["server"]:
                if s in server_header:
                    confidence += 0.40
                    matched_reasons.append(f"Server header '{server_header}' identifies {vendor}")

            # Check cookies
            for c in rule["cookies"]:
                for ck in cookies_lower.keys():
                    if re.search(c, ck, re.IGNORECASE):
                        confidence += 0.35
                        matched_reasons.append(f"Cookie '{ck}' matches {vendor}")

            # Check body patterns
            for pat in rule["body_patterns"]:
                if re.search(pat, body_lower):
                    confidence += 0.40
                    matched_reasons.append(f"Response body signature matches {vendor}")

            if confidence > 0.30:
                confidence = min(0.99, confidence)
                detected_wafs.append({
                    "vendor": vendor,
                    "confidence": round(confidence, 2),
                    "reasons": matched_reasons,
                    "evasion_hints": rule["evasion_hints"],
                })

        if detected_wafs:
            # Sort by highest confidence
            detected_wafs.sort(key=lambda x: x["confidence"], reverse=True)
            primary = detected_wafs[0]
            return {
                "detected": True,
                "vendor": primary["vendor"],
                "confidence": primary["confidence"],
                "all_matches": detected_wafs,
                "evasion_hints": primary["evasion_hints"],
            }

        return {
            "detected": False,
            "vendor": None,
            "confidence": 0.0,
            "all_matches": [],
            "evasion_hints": [],
        }


waf_detector = WafDetector()
